### ISSUE TITLE
Multiple backends and removal of _sim_backend global var

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#10]
As part of restructuring, I wanted to make the signal.py file currently in ophyd_async.epics._signal smaller, as this actually contains a lot of classes/concepts within it which can make it tedious to read through. In doing so, I was reminded of the existence of `_sim_backend`, a global variable that gets appended to in the connect() method of any sim device.

The main utility of this, is then one can call set_sim_value() and use other helper methods that directly interact with a SimSignalBackend rather than a SignalBackend, like ._set_value, which bypasses caget/pv access. My understanding is this is mostly to help with tests.

However, I don't think it's very neat. I'd like to get rid of this, and either change the tests so they interact with the signals/backends as if they were 'real' (i.e. having to await them) or just handle the backend directly from the signal object and include some '#type: ignore' comments in case mypy isn't placated.

In general, I think signals should be able to have more than one backend, and a user should be able to switch between them in the long run; why wouldn't you, if it's available? Or, do we just want to restrict users here and now and say, either you're using CA or PVA and there's no in-between.

**Comment by coretl** [comment]
Will be handled in #94
