### ISSUE TITLE
Consider Path Signals

### ISSUE THREAD

**Issue by callumforrester** [bluesky/ophyd-async#122]
Some string PVs are intended only to store file paths, e.g. the HDF5 plugin write path. Perhaps there is value in representing these with a `Signal[Path]` rather than a `Signal[str]` and performing some validation on input values.

See [ophyd_async.epics.areadetector.writers.nd_file_hdf.NDFileHDF](https://github.com/bluesky/ophyd-async/blob/641894d6404072f4e3413a82383ef257186d0735/src/ophyd_async/epics/areadetector/writers/nd_file_hdf.py#L19) for an example.

@coretl any thoughts?

**Comment by DominicOram** [comment]
:+1: from me

**Comment by coretl** [comment]
Could be done, but I'd say this is low priority compared with the other things we're doing

**Comment by callumforrester** [comment]
Will leave it as a good first issue then

**Comment by coretl** [comment]
Closing as `PathProvider` makes the above usecase less compelling. We can revisit after 1.0 if this is still needed
