### ISSUE TITLE
Add Multipliers to prepare

### ISSUE THREAD

**Issue by abbiemery** [bluesky/ophyd-async#130]
We want to be able to run one detector twice as fast as another but we still need to correlate the multiple fast detector frames to the single slow detector frame (In the case of twice as fast, 2:1). We do this my making `TriggerInfo.num` twice as big in the faster detector. This trigger info is passed to the detector in its prepare method. If we also set `TriggerInfo.multipler` then this can make it into the stream resource so downstream processes can zip the files together. 

Depends on #129

**Comment by jwlodek** [comment]
Should `TriggerInfo.num` remain the number of triggers for the detector instance itself, or should it now be the number of triggers for the slowest detector in the scan, since we can presumably get the number of triggers for each detector based on the multiplier?

**Comment by coretl** [comment]
> Should `TriggerInfo.num` remain the number of triggers for the detector instance itself, or should it now be the number of triggers for the slowest detector in the scan, since we can presumably get the number of triggers for each detector based on the multiplier?
> As best as I can tell, it would be easier to use the baseline `num` for triggers, since the original trigger_info is coming from the higher level HardwareTriggeredFlyable class, with the same one being passed to each detector in `prepare`. I guess the question becomes should each `StandardDetector` have it's `TriggerInfo` updated to the actual `num`, or should we leave it as the baseline frequency and recalculate actual num triggers whenever needed with the multiplier.


I think it should be the number of triggers sent to the detector. We will use a PandA Pulse block to take the input pulse train and multiply it up, changing the livetime and deadtime too, so it makes sense for it to calculate a new `TriggerInfo` with this information and send it to `detector.prepare()`. The only reason the detector needs the multiplier is so that it can put the right information in the descriptor and StreamResource documents.

**Comment by coretl** [comment]
Depends on #127

**Comment by coretl** [comment]
Do this as part of #314

**Comment by coretl** [comment]
Do this as part of #314
