### ISSUE TITLE
Enums with blank entries break PandA

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#149]
In #147 CA and PVA enum handling was consolidating, but this line was lost:
https://github.com/bluesky/ophyd-async/blob/373b3358686f73457661fdd607aabaae502f2534/src/ophyd_async/epics/_backend/_p4p.py#L224

A test case needs adding in `test_records.db` with blank `ZNAM` and `ONAM` fields to demonstrate, then the line can be added back in

**Comment by coretl** [comment]
database side is something like:
```
record(bo, "$(P)emptyenum") {
  field(VAL, "1")
  field(PINI, "YES")
}
```
Which should give you an enumeration with 2 choices: `["", ""]`

**Comment by DiamondJoseph** [comment]
Is blank enum name also valid for CA or just PVA?

**Comment by coretl** [comment]
both
