### ISSUE TITLE
GeneratedChoices enum can't handle signals with choices ["", ""]

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#15]
when startingup an IOC, some enums have ZNAM and ONAM set to "", which means ophyd falls over when trying to set up the enums dynamically (e.g. as for a panda), i.e. when the datatype for `epics_signal_xyz` is set to `None`, because of this line in `_p4p.py`:

```
enum_class = Enum("GeneratedChoices", {x: x for x in pv_choices}, type=str)  # type: ignore
```

to fix, for now we could do the following check beforehand:

```
if "" in pv_choices:
    pv_choices = tuple(["_" if i=="" else i for i in pv_choices])
```
i.e. meaning there are no choices for this PV.

This is only a temporary fix; really we should think about whether these PV's by default should have ZNAM and ONAM set to something, which is a pandablocks-ioc issue.

**Comment by coretl** [comment]
Fixed in #152
