### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by callumforrester** [bluesky/ophyd-async#156]
This repository takes up 251MB at time of writing and took me several minutes to clone. Currently unsure why or if there is any unnecessary history that can be removed. @coretl any thoughts?

**Comment by coretl** [comment]
Size of `gh-pages`? Once you've adopted copier you could delete all the branches and then squash merge them down...

**Comment by callumforrester** [comment]
Okay, this now depends on #158

**Comment by abbiemery** [comment]
#158 is now merged. What do I have to do now to reduce the size of these pages?

**Comment by coretl** [comment]
- Checkout `gh-pages`
- Delete all the directories apart from `main` and the release tags
- Make sure that `switcher.json` only has directories that exist in it
- Delete `.doctrees/environment.pickle` from each directory
- Push
- Check the landing page for all versions works on github,io
- If that is all fine the make a local `gh-pages-backup` branch on `origin/gh-pages`
- Then squash `gh-pages` branch to a single commit and force push it
- Check again that landing page for all versions works on github.io
- Check a fresh clone is much smaller

**Comment by abbiemery** [comment]
```Receiving objects: 100% (7809/7809), 7.64 MiB | 6.90 MiB/s, done.```

Done :)
