### ISSUE TITLE
Consider the interface to `DeviceControl.arm`

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#162]
This parameter is ignore but it _has_ to be there to satisfy the interface, meaning the user can pass whatever they want. Possible an issue we should raise with ophyd-async.

_Originally posted by @callumforrester in https://github.com/DiamondLightSource/dodal/pull/402#discussion_r1541443800_

**Comment by callumforrester** [comment]
Relevant discussion: https://github.com/bluesky/ophyd-async/pull/159#discussion_r1541271352

**Comment by coretl** [comment]
Closing in favour of #405
