### ISSUE TITLE
Enable continuous scanning on a single axis with a motor controlled by a Zebra

### ISSUE THREAD

**Issue by stan-dot** [bluesky/ophyd-async#172]
On i20-1, the test bed for the flagship SWIFT beamline, continuous motion is enabled by the use of a Zebra motion controller. SWIFT may be using a PandA to accomplish this (?), but other beamlines will still make use of the Zebra.

A TriggerLogic constructed with a Zebra, analogously to the [PandATriggerLogic used on i22](https://github.com/DiamondLightSource/i22-bluesky/blob/cba944bae3defc87afe640c77de36dd5bc825ddb/src/i22_bluesky/plans/fly_collect.py#L26), should be implemented, which can drive a single axis while periodically or spatially-resolving collections from a number of ophyd-async Detectors.

i20-1 ran a continuous scan in the x axis of the TurboSlit device, to scan a bandwidth of polychromatic beam. This use-case seems a sensible starting point in the move towards a more generic implementation of trajectory scanning, especially if it can be constructed as an instance of a ScanSpec trajectory

**Comment by DominicOram** [comment]
What is required for this? We've recently done some work to convert the zebra to ophyd-async in dodal: https://github.com/DiamondLightSource/dodal/pull/382

**Comment by DiamondJoseph** [comment]
Good catch, I'd forgotten about #382 and had naively found the couple of commits from last year of adding a basic Zebra before the repository was renamed. I think what we actually want is [a ZebraTriggerLogic analogous to the PandA one on i22](https://github.com/DiamondLightSource/i22-bluesky/blob/cba944bae3defc87afe640c77de36dd5bc825ddb/src/i22_bluesky/plans/fly_collect.py#L26), which may end up being moved into ophyd-async (I believe it's being refactored into a SequenceTableTriggerLogic?)

I need to talk to @coretl about the plan for ScanSpec-driven generic flying

**Comment by DominicOram** [comment]
Ok, could we rename this issue/add a description to make it clear what the discussion needs to be and the acceptance criteria to either have that discussion or to implement the solution? It would be useful for us, whilst we are working on the zebra atm, to have some visibility over what direction you might want to take it in.

**Comment by coretl** [comment]
I would be inclined to leave the zebra support in dodal. We're never going to touch the EPICS code, and hopefully most of the usage will switch to PandA when we switch to bluesky
