### ISSUE TITLE
Make common code from the PandA HDF writer and AreaDetector HDF Writer

### ISSUE THREAD

**Issue by olliesilvester** [bluesky/ophyd-async#182]
After https://github.com/bluesky/ophyd-async/pull/141, there is a lot of duplicated code in the AreaDetector and PandA HDF writer. In the respective `hdf_writer` files:
- There are a number of similarities in the `open` functions
- `observe_indices_written` is identical
- `collect_stream_docs` is similiar

In `panda_hdf.py` and `_hdffile.py`:
`stream_resources` and `stream_data` are the same. The `_HDFFile` class itself is also almost the same

We should tidy this up by putting the above code in a common place

**Comment by coretl** [comment]
Closing in favour of #173
