### ISSUE TITLE
Log everytime a signal is updated or sends an update

### ISSUE THREAD

**Issue by DominicOram** [bluesky/ophyd-async#195]
To aid in debugging beamline issues it would be good to know the following:

* When a signal gets updated from an external source (e.g. a PV). In this case we will want to know:
    * The name of the signal
    * The name of the PV
    * The value we got
    * The old value (if possible)
    * Metadata about the update e.g. the EPICS timestamp
* When a signal has been written to we would also like to log:
    * The name of the signal
    * The name of the PV
    * The value we got
    * The old value (if possible)
 
It should be obviously easy from the logs to differentiate between these two cases. It should be logged as debug as it will be a lot of info

**Comment by coretl** [comment]
To expand this slightly, we should add log messages to these functions:
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L70 saying we are about to connect
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L176 saying what value we got from the backend
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L94 saying that we made a subscription
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L110 saying that we got an update to the subscription
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L97 saying we closed the subscription
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L211 to say we are about to put a value to the backend, then one after to say the put is complete
- https://github.com/bluesky/ophyd-async/blob/e54c91ce826f76a7398178b93243b980f796c102/src/ophyd_async/core/signal.py#L233 to say we are about to put the default value to the backend, and one to say it is complete

For those last 2, you will have to use the `@AsyncStatus.wrap` decorator a bit like https://github.com/bluesky/ophyd-async/blob/7be73e3ce0f79fca2e02f77f366792ee84586ed7/src/ophyd_async/core/standard_readable.py#L43 so you can put a log message before and after the await

**Comment by callumforrester** [comment]
Reviewers: @coretl @ZLLentz

**Comment by olliesilvester** [comment]
In original Ophyd, the logs appended the name of the `ophyd object ` at the beginning of the message, but by default these objects didn't have a name. Should we keep it this way? It might be nicer for the default name of an `ophyd_async` `device` to be a string of its type.

**Comment by coretl** [comment]
These objects should be named before connection, so there should be something useful in `Device.name` most of the time

**Comment by coretl** [comment]
Fixed by #275
