### ISSUE TITLE
Test helpers for assering value, reading and configuration

### ISSUE THREAD

**Issue by callumforrester** [bluesky/ophyd-async#199]
[Dodal](https://github.com/DiamondLightSource/dodal) developers have produced various useful ways to test ophyd-async devices such as [`verify()`](https://github.com/DiamondLightSource/dodal/blob/6b43b48fcb388c43f919b7d0866fb44d8f8199ee/tests/devices/unit_tests/test_synchrotron.py#L201). Some of these should probably make it back into `main` and sit alongside other helper functions like `set_sim_signal`.

I think we need 3 helper functions:
- `assert_value(signal: SignalR[T], value: T)`
- `assert_reading(readable: Readable, reading: Reading)`
- `assert_configuration(readable: Readable, configuration: Configuration)`
 
## Acceptance Criteria
- Functions in ophyd-async
- Tests provided
- Docs provided where appropriate
- Issues raised in dodal to replace `verefy()` and any other old functions that can be superseded

**Comment by callumforrester** [comment]
@coretl

**Comment by coretl** [comment]
Possibly also want `assert_emitted` from #206
