### ISSUE TITLE
Create class for the areaDetector statistics plugin.

### ISSUE THREAD

**Issue by jwlodek** [bluesky/ophyd-async#213]
Several of our beamlines make extensive use of the statistics plugin to collect metadata (max pixel value, average value, etc.). We should add support for using this plugin with `ophyd-async`.

**Comment by callumforrester** [comment]
Reviewers: @RobertSchaffer1 @DiamondJoseph

**Comment by DiamondJoseph** [comment]
Here's my incredibly naive initial thoughts on it

https://github.com/bluesky/ophyd-async/pull/178

We want to be able to instantiate various AreaDetector implementations optionally with the Stats plugin (and likely other plugins in a chain later) and have an easy way of adding them to the scalar_signals of the detector (probably non-scalar too).

**Comment by DiamondJoseph** [comment]
@jmaruland is this still ongoing?

**Comment by ZohebShaikh** [comment]
closed by #468
