### ISSUE TITLE
Create helper functions for making soft signals

### ISSUE THREAD

**Issue by DominicOram** [bluesky/ophyd-async#215]
Creating a soft signal is a bit long winded, we should make helper functions like https://github.com/DiamondLightSource/dodal/blob/main/src/dodal/devices/ophyd_async_utils.py

## Acceptance criteria
* There are helper functions in `ophy-async` for making soft signals
* We remove the ones in dodal

**Comment by callumforrester** [comment]
Reviewers: @DominicOram @coretl @mrakitin

**Comment by jsouter** [comment]
See https://github.com/bluesky/ophyd-async/pull/217, as I say, can be moved if it's not core enough to be in core.signal
