### ISSUE TITLE
Remove the move!

### ISSUE THREAD

**Issue by gilesknap** [bluesky/ophyd-async#228]
The opyhd_async.epics.morot.Motor.move() function does a synchronous move.

@coretl asserts that this is a bad thing as it requires an active RunEngine event loop.

Instead use:
```
await my_motor.set(position)
```

**Comment by gilesknap** [comment]
@coretl in fact doing await set will return as soon as the demand is updated - what should the semantics be for waiting for a move to complete?

**Comment by coretl** [comment]
Done in #117
