### ISSUE TITLE
Support extensible enums

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/ophyd-async#238]
For the Aravis detector, we need to support a dynamically extensible enumeration of values for some signals (e.g. the AravisTriggerSource, which we rely on the values Free_Run and Line_1 being present, but there may also be Line_2, Line_3...).

This may be accomplished by a new class of Signal that has a write_pv of type Enum and a read_pv of type str, which would require SignalBackend to take two generic arguments. The existing Signal implementations then have a single Generic bound which is passed into both generic bounds of the backend and the new implementation has bounds of [str, enum_class] for read, write respectively.

This ticket is necessary for #190

**Comment by coretl** [comment]
Discussed this with @evalott100 and she suggested:
```python
@dataclass
class RuntimeEnumDataclass:
    choices: Sequence[str]
    @classmethod
    def __getitem__(cls, *items: str) -> "RuntimeEnum":
        return cls(items)

if TYPE_CHECKING:
    RuntimeEnum = Literal
else:
    RuntimeEnum = RuntimeEnumDataclass

# aravis_something.py
class AravisCamera(Device):
    def __init__(self, prefix):
        self.trigger_mode = epics_signal_rw(RuntimeEnum["Line1", "FixedRate"], prefix + "TriggerMode")
        ...

# _aioca.py
def make_converter(...):
    ...
    elif isinstance(datatype, RuntimeEnum):
        assert set(datatype.choices).issubset(pv_choices)
    ...
```

We were unable to come up with a better name than `RuntimeEnum`, but others may have better ideas...
