### ISSUE TITLE
The docs are now worse?

### ISSUE THREAD

**Issue by abbiemery** [bluesky/ophyd-async#259]
I can't tell from the existing issues if there is visibility on this, but the docs are now much worse than before we changed the template.

Templates are visible, things are missing.
![image](https://github.com/bluesky/ophyd-async/assets/57836554/0284ad85-b3b9-471a-a9fd-4b45fb0dab4d)

This is worse to navigate.
![image](https://github.com/bluesky/ophyd-async/assets/57836554/79cf5431-5b9f-45ac-b9c6-9f368be9d2d1)

The dev instructions have gone?

**Comment by joeshannon** [comment]
For the `:::` it looks like it needs an extension enabling:

https://github.com/DiamondLightSource/blueapi/blob/c3d1ccd89dd22725931b628c857f3c953d2e3486/docs/conf.py#L55

In the current copier template the Developer and User guides have been merged. The other docs such as running tests etc. are now linked directly to the copier template from how-to/contribute.html.

**Comment by abbiemery** [comment]
> In the current copier template the Developer and User guides have been merged.

But, why? There are sometimes very good reasons to have these separate. I know this isn't an argument because the decision has been made but this feels like a step back to me.

**Comment by coretl** [comment]
> > In the current copier template the Developer and User guides have been merged.
> 
> But, why? There are sometimes very good reasons to have these separate. I know this isn't an argument because the decision has been made but this feels like a step back to me.

The decision was made because there is a blurry boundary between developer and user guides, and feedback was that people ended up missing docs because they weren't reading the right section. Most of the developer guide has now been put in the copier template docs and linked from the repo `how-to/contribute` guide. Suggestions on what should be in this guide welcome.
