### ISSUE TITLE
Features to allow Devices to be connected up front, or lazily connected in plans

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#265]
https://github.com/DiamondLightSource/dodal/issues/415#issuecomment-2079651830 summarizes a discussion on Device connection. The strategy we would like to support in ophyd-async is:
- Device connection can be kicked off at any point, but we would like to ensure a Device is connected before we use it in a plan
- If we keep track of the connect task then we can make subsequent calls to connect return immediately if a successful connect has been done
- This means we can write an `ensure_connected(*devices)` plan stub that can be used in plans to run that connect method, which will do no I/O if the Device is already connected
- We need a method of doing a reconnect if we want to make sure the Device is still there

This ticket is for the following:

## New ADR

Describing strategies for Device connection

## `Device.connect`

Change so it looks like:
```python
class Device:
    # None if connect hasn't started, an Event if it has, a set Event if it's done
    _connect_task: Optional[asyncio.Task] = None
    async def connect(self, mock: bool = False, timeout: float = DEFAULT_TIMEOUT, force_reconnect=False):
        previous_connect_ok = self._connect_task and self._connect_task.done() and not self._connect_task.exception()
        if force_reconnect or not previous_connect_ok:
            # Kick off a connection
            coros = {
                name: child_device.connect(mock, timeout=timeout)
                for name, child_device in self.children()
            }
            self._connect_task = asyncio.create_task(wait_for_connection(**coros))
        # Wait for it to complete
        await self._connect_task
```

## New `ophyd_async.planstubs.ensure_connected`
```python
def ensure_connected(*devices: Device, mock: bool = False, timeout: float = DEFAULT_TIMEOUT, force_reconnect=False):
    coros = {device.name: device.connect(mock, timeout, force_reconnect) for device in devices}
    bps.wait_for([wait_for_connection(**coros)])
```

**Comment by jwlodek** [comment]
This would be a very helpful feature for us at NSLS-II. Currently the strategy has been "comment out the devices you are not using..."
