### ISSUE TITLE
Write planstub for the current standard fly-scan

### ISSUE THREAD

**Issue by abbiemery** [bluesky/ophyd-async#278]
We currently have a unified way to stage, prepare, collect etc with a set of detectors and a flyer. It is worth having a plan stub for this within ophyd-async so we don't keep re-writing this in each of the beamline-bluesky repos.

**Comment by callumforrester** [comment]
Is this the same as/related to https://github.com/bluesky/bluesky/issues/1641?

**Comment by abbiemery** [comment]
It is related to. This plan should end up using the plan in 1641, but the plan in here will encompass the preparing etc.
