### ISSUE TITLE
Document physical connections from PandAs to controlled hardware

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/ophyd-async#284]
A PandA has multiple TTL ins, outs. These should be documented (in the device factory function docstrings?) such that it can be determined which PandA(s) may be used to drive certain hardware/scans: assuming that this docstring is kept up to date.

Acceptance criteria:
- [ ] It can be determined by someone instantiating a PandA which devices it will be able to trigger
- [ ] Multiple PandAs on a beamline may be physically wired to overlapping subsets of the devices on the beamline
- [ ] This information can be propagated into blueapi etc.

**Comment by coretl** [comment]
Will discuss this as part of #111
