### ISSUE TITLE
Investigate if we can get rid of the `await coro` in `test_async_status_success_if_cancelled`

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#288]
Unfortunately not really applicable in this case, see: https://github.com/bluesky/ophyd-async/tree/try_with_asyncio_timeout which has the same problem but is much more complicated

_Originally posted by @dperl-dls in https://github.com/bluesky/ophyd-async/pull/176#discussion_r1586304077_

**Comment by jsouter** [comment]
I think this was addressed here: https://github.com/bluesky/ophyd-async/pull/318

**Comment by coretl** [comment]
Good point!
