### ISSUE TITLE
Enable `SLF001` ruff check

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#299]
As per https://github.com/DiamondLightSource/python-copier-template/issues/154

**Comment by stan-dot** [comment]
`SLF001` is about private class method/property access

**Comment by coretl** [comment]
Waiting for #383

**Comment by coretl** [comment]
@abbiemery I merged this into the copier template main, please could you try doing a `copier update --vcs-ref=main` and check this works?

**Comment by abbiemery** [comment]
I did the changes to ophyd-async that are JUST the SLF ones, as the other ones on the copier template bring in a lot of errors to fix. I suggest we merge the SLF changes now, and make issues to adopt the other ones. 

https://github.com/bluesky/ophyd-async/pull/483
