### ISSUE TITLE
Defer creation of HDF5 file until prepare/trigger

### ISSUE THREAD

**Issue by callumforrester** [bluesky/ophyd-async#314]
Calling in `prepare`/`trigger` rather than `stage` would mean we can tie the file path into contextual information about the run. `stage` is normally called before `open_run` so creating the file in `stage` means the run does not exist at the time of creation. 
Any solution has to be mindful of pre-declare, the file must exist by the time `describe` is called, i.e. the `declare_stream` plan.

**Comment by abbiemery** [comment]
This is needed so we can use multipliers. Closing old issue #129 in favour of this.

**Comment by coretl** [comment]
Suggested changes to `StandardDetector`:
- `stage()` brings the device into a state that is ready to start *any* scan, no matter of its parameters
- `prepare()` will set multipliers, and get a filename, and call `writer.open()`
- if `prepare()` has not been called with a software trigger mode before `trigger()`, then call it for the user with default parameters

Should be done with knowledge of how the interface between `StandardDetector` and `DetectorController`: https://github.com/bluesky/ophyd-async/issues/405
