### ISSUE TITLE
Add two additional fly plan stubs - one that uses PCOMP, and one that uses a PULSE

### ISSUE THREAD

**Issue by jwlodek** [bluesky/ophyd-async#334]
It would be good to have built in plan stubs that allow for you to run flys using these two other methods.
```[tasklist]
### Tasks
- [ ] https://github.com/bluesky/ophyd-async/issues/375
- [ ] https://github.com/bluesky/ophyd-async/issues/376
```

**Comment by coretl** [comment]
This is to make:
- position triggered pulses
- time based pulses
within a postion based gate
