### ISSUE TITLE
Convert signal readings and `get_values` to pure python types

### ISSUE THREAD

**Issue by DominicOram** [bluesky/ophyd-async#360]
When you call `get_reading` or `get_value` on a signal it returns an `aioca` channel access type rather than the pure python type e.g. `ca_int` rather than `int`. This has caused issues downstream e.g. https://github.com/DiamondLightSource/hyperion/issues/1417#issuecomment-2144684981. We should do the conversion every time the signal is read or the value is taken from it.

**Comment by coretl** [comment]
Is this fixed?

**Comment by coretl** [comment]
@rtuck99 is this fixed now?

**Comment by DominicOram** [comment]
Yes, I believe this is fixed
