### ISSUE TITLE
`StandardReadable` breaks with nested hinted signals

### ISSUE THREAD

**Issue by callumforrester** [bluesky/ophyd-async#365]
When creating a `StandardReadable` with hinted signals, and then nesting it inside another `StandardReadable`, ophyd-async crashes with the following error:

```shell
AssertionError: Hint fields  overrides existing hint
```

The bug can be reproduced, along with the full stacktrace, via the following failing test:

```python
def test_standard_readable_add_children_multi_nested():
    inner = StandardReadable()
    outer = StandardReadable()
    with inner.add_children_as_readables(HintedSignal):
        inner.a, _ = soft_signal_r_and_setter(float, initial_value=5.0)
        inner.b, _ = soft_signal_r_and_setter(float, initial_value=6.0)
    with outer.add_children_as_readables():
        outer.inner = inner
```

What I _think_ is going on: Let's say we called `outer.hints`. This would merge the dicts produced by `inner.a.hints` and `inner.b.hints`, so it would look something like: `{"inner-a-fields": [""], "inner-b-fields": [""]}`. `"fields"` is the produced by a `HintedSignal` and `inner-a/b` is prepended to it by `StandardReadable`.

If `outer.hints` were somehow called before `outer`'s super constructor, this could be a problem. The super constructor is where `inner.a` and `inner.b` are actually assigned names. Before that, their names are both `""`, meaning their hints output would be `{"fields": [""]}`. The `hints` property does not allow name clases between nested devices and raises the error shown.

The final piece of the puzzle: Where is `.hints` being called from before we even reach the super constructor? It appears to be the type check within `add_children_as_readables`:

```python
if isinstance(obj, HasHints):
    self._has_hints += (obj,)
```

`HasHints` is a `@runtime_checkable` protocol which specifies `hints` as a property. It seems that protocols, when checked at runtime, actually _access_ their properties, leading to weird side effects. I have confirmed this by playing around with a python shell.

**Comment by coretl** [comment]
As discussed with @callumforrester , probable fix is to make hints empty if name is not set
