### ISSUE TITLE
DeviceCollector throws some exceptions away in tests that use it

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#39]
Recently, when writing a bit of code for blueapi (https://github.com/DiamondLightSource/blueapi/pull/321/) we found that if we tried to test the Device Collector (as per https://github.com/bluesky/ophyd/pull/1151)

The tests in Callum's PR seem to fail for the original Device Collector if assert statements on the logs are present. This is odd behaviour and should be fixed.

**Comment by coretl** [comment]
Fixed by #97
