### ISSUE TITLE
Ensure connected plan stub not propogating connection errors

### ISSUE THREAD

**Issue by evalott100** [bluesky/ophyd-async#413]
In writing a test during https://github.com/bluesky/ophyd-async/pull/368, @stan-dot and I found a problem in `ensure_connected`:

https://github.com/bluesky/ophyd-async/blob/9d243e6f1d44f45b3a15e1e13af41b6497a9796f/tests/core/test_device.py#L162-L168

In this code one of the `MockSignalBackends` is swapped out for a subclass of `MockSignalBackend` which raises an error every other connect. The connect on one of the motor signals fails with `RuntimeError` however `ensure_connected` doesn't propogate this error...

Swapping the plan stub for

``` python
    with pytest.raises(NotConnected, match="RuntimeError: connect fail"):
        await test_motor.connect(mock=True, force_reconnect=True)
```

We see the error propogate as expected.

@coretl @ZohebShaikh have I misunderstood the behaviour of `ensure_connected`? It seems there aren't any tests using it where a device would fail to connect.

**Comment by coretl** [comment]
This is a bug either in the run engine handling of `wait_for` or in `ensure_connected`.

The RE calls `asyncio.wait_for([futs])`, and checks they complete in the given time, but then throws away the return value.

Possible fixes:
1. Make RE return the completed futures from `bps.wait_for`
2. Make `ensure_connected` create futures in the lambda and stash them so they can be checked after the call to `bps.wait_for`

@tacaswell thoughts?

**Comment by tacaswell** [comment]
lean to option 1.

**Comment by coretl** [comment]
Tracked as https://github.com/bluesky/bluesky/issues/1756

Once this is completed then `ensure_connected` should check the `.exception()` of the futures returned from `bps.wait_for`

**Comment by tacaswell** [comment]
Would it make sense to have `_wait_for` raise itself?

**Comment by coretl** [comment]
> Would it make sense to have `_wait_for` raise itself?

probably not, it takes multiple things, so what happens if only one fails? At the moment it calls `asyncio.wait` which returns rather than raises, so makes sense to mimic this

**Comment by stan-dot** [comment]
in `blueapi` [PR 515](https://github.com/DiamondLightSource/blueapi/pull/515) I encountered this error too in `ensure_connected`.possibly related: 

```src/blueapi/worker/reworker.py:31: in <module>
    from .task import Task
src/blueapi/worker/task.py:5: in <module>
    from ophyd_async.plan_stubs import ensure_connected
/venv/lib/python3.11/site-packages/ophyd_async/plan_stubs/__init__.py:2: in <module>
    from .fly import (
/venv/lib/python3.11/site-packages/ophyd_async/plan_stubs/fly.py:9: in <module>
    from ophyd_async.panda._table import SeqTable, SeqTableRow, seq_table_from_rows
/venv/lib/python3.11/site-packages/ophyd_async/panda/__init__.py:9: in <module>
    from ._hdf_panda import HDFPanda
/venv/lib/python3.11/site-packages/ophyd_async/panda/_hdf_panda.py:11: in <module>
    from ophyd_async.epics.pvi import create_children_from_annotations, fill_pvi_entries
/venv/lib/python3.11/site-packages/ophyd_async/epics/pvi/__init__.py:1: in <module>
    from .pvi import PVIEntry, create_children_from_annotations, fill_pvi_entries
/venv/lib/python3.11/site-packages/ophyd_async/epics/pvi/pvi.py:23: in <module>
    from ophyd_async.epics._backend._p4p import PvaSignalBackend
/venv/lib/python3.11/site-packages/ophyd_async/epics/_backend/_p4p.py:11: in <module>
    from p4p import Value
/venv/lib/python3.11/site-packages/p4p/__init__.py:14: in <module>
    from .wrapper import Value, Type
/venv/lib/python3.11/site-packages/p4p/wrapper.py:5: in <module>
    from . import _p4p
src/p4p/_p4p.pyx:1: in init p4p._p4p
    ???
E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by evalott100** [comment]
> in `blueapi` [PR 515](https://github.com/DiamondLightSource/blueapi/pull/515) I encountered this error too in `ensure_connected`.possibly related:

This is an error introduced by the recent numpy v2 update in p4p:
https://github.com/mdavidsaver/p4p/issues/145

**Comment by coretl** [comment]
> > in `blueapi` [PR 515](https://github.com/DiamondLightSource/blueapi/pull/515) I encountered this error too in `ensure_connected`.possibly related:
> 
> This is an error introduced by the recent numpy v2 update in p4p: [mdavidsaver/p4p#145](https://github.com/mdavidsaver/p4p/issues/145)

The relevant ophyd-async ticket is https://github.com/bluesky/ophyd-async/issues/387
