### ISSUE TITLE
Move Flyable dataclasses to pydantic dataclasses

### ISSUE THREAD

**Issue by olliesilvester** [bluesky/ophyd-async#435]
After discussion with @coretl , we think it would be nice to convert our dataclasses for flyable information, eg `TriggerInfo` in `detector.py`, to pydantic dataclasses, as this would give us runtime type validation. See https://github.com/bluesky/ophyd-async/pull/425 for an example

## Acceptance Criteria
All dataclasses associated with a `Flyable` is now done in pydantic. I may have missed some, but these include:
- `TriggerInfo`
- `PcompInfo`
- `SeqTableInfo`

**Comment by evalott100** [comment]
Will include in

https://github.com/bluesky/ophyd-async/pull/430
