### ISSUE TITLE
Overlapping logic with hdf writers

### ISSUE THREAD

**Issue by subinsaji** [bluesky/ophyd-async#452]
There is a lot of overlapping logic with `hdf_writer.py` :
 https://github.com/bluesky/ophyd-async/blob/0269697acd9de1ff645fdc40aaf7937c6f346bd4/src/ophyd_async/epics/areadetector/writers/hdf_writer.py#L81-L112

and also with panda `_hdf_writer.py` : https://github.com/bluesky/ophyd-async/blob/0269697acd9de1ff645fdc40aaf7937c6f346bd4/src/ophyd_async/panda/writers/_hdf_writer.py#L69-L79

From a DRY point of view, we can reduce this repeating logic

_Originally posted by @subinsaji in https://github.com/bluesky/ophyd-async/issues/436#issuecomment-2225834857_

**Comment by coretl** [comment]
Fixed in #182
