### ISSUE TITLE
Improve `connect` protocol to take timeout

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#48]
At the moment we have:
https://github.com/bluesky/ophyd-async/blob/f1b4aba227ee6b568718c170ced6378a744abf99/src/ophyd_async/core/device.py#L53-L65

This doesn't take timeout, so to add timeout on top we wrap with `asyncio.wait` or similar (like other primitives in the asyncio library). Unfortunately this makes logging the error difficult as `connect` calls recursively connect child devices. The way we report reasonable errors at the moment is to catch the `CancelledError` that is injected when the task times out, and raise `NotConnectedError` with the name of the signal in question, accumulating them in the parent until we produce a single top level `NotConnectedError` with all the failing signals:

https://github.com/bluesky/ophyd-async/blob/f1b4aba227ee6b568718c170ced6378a744abf99/src/ophyd_async/core/utils.py#L26-L53

This is horrible. It also bites people who `await device.connect()` rather than using `asyncio.wait` like in https://github.com/DiamondLightSource/dodal/issues/223.

@callumforrester suggested a better way, pass the timeout down, then let each child produce a `class ConnectTimeoutError(TimeoutError)` when it times out, then assemble it at the top level with an `asyncio.gather(*coros, return_exceptions=True)`, squashing `ConnectTimeoutError`s into a single one.

This would change the signature to:

```python
async def connect(self, sim: bool = False, timeout: float = DEFAULT_TIMEOUT):  
```

with each concrete class raising `ConnectTimeoutError` if it times out, then `wait_for_connection` doing the squashing of `ConnectTimeoutErrors`.

**Comment by olliesilvester** [comment]
An `ophyd_async` device timed out on Hyperion yesterday, very difficult to diagnose without knowing what device / signal timed out, so this change will be very useful
