### ISSUE TITLE
Add context for callback to be removed from sim signal

### ISSUE THREAD

**Issue by DominicOram** [bluesky/ophyd-async#49]
When writing tests I want to simulate some basic signal behaviour e.g. writing to one signal will put to another. However, I would like to make sure this behaviour is properly cleaned up between tests. I can simulate with `set_sim_callback` and `set_sim_value` but there is no way to remove this callback.

## Acceptance Criteria
* There is a context that removes callbacks from simulated signals on cleanup

**Comment by coretl** [comment]
I like this being a context, then making it fire on put rather than on every update, as that is what the tests want

**Comment by DominicOram** [comment]
Taken myself off this as @coretl said they will find someone else to pick it up. It's not urgent from our perspective

**Comment by coretl** [comment]
I think this will be fixed if we have a generic Mock backend in #94

**Comment by coretl** [comment]
Fixed by #94
