### ISSUE TITLE
Make `SimMotor` produce an updating status

### ISSUE THREAD

**Issue by callumforrester** [bluesky/ophyd-async#506]
As a developer I would like to use `SimMotor` with `RE.waiting_hook` to make progress bars and similar. This will require the motor's status to update periodically with its progress.

**Comment by coretl** [comment]
The code is written such that this should already be happening:
https://github.com/bluesky/ophyd-async/blob/9701810b9dff3207894982993033214b3e958707/src/ophyd_async/sim/demo/_sim_motor.py#L87-L93

If it is not happening then this is a bug that needs investigating

**Comment by callumforrester** [comment]
Sorry, this was my mistake, I thought I had closed this. It behaves as-expected, although only if the motor is not in instantaneous mode, but that seems reasonable.
