### ISSUE TITLE
Discussion: Should children automaticaly traverse more of the object

### ISSUE THREAD

**Issue by DominicOram** [bluesky/ophyd-async#52]
Currently the `children` function on a device checks if the `Device` has any direct attributes that are `Devices`. This results in the following:
```python
class MyDevice(Device):
    def __init__():
        self.channels = [epics_signal_r(float, f"A"), epics_signal_r(float, f"B")]

my_device.connect() # channels will not get connected here
```
The fix for this is something like:
```python
class MyDevice(Device):
    def __init__():
        self.channels = [epics_signal_r(float, f"A"), epics_signal_r(float, f"B")]
   def children():
       for signal in self.channels:
           yield signal
       return super().children()
```

@coretl, @callumforrester - I feel like we may have discussed this already but needs writing down

## Acceptance Criteria
* We decide if `children` should be more clever
* Decision and reasoning is documented
* If the above behaviour remains it should be documented as a gotcha

**Comment by coretl** [comment]
If you use a `DeviceVector` (and please write docs for it too!) then this will work

**Comment by callumforrester** [comment]
Docs for `DeviceVector` in #183 

@DominicOram does it satisfy your requirements?

**Comment by DominicOram** [comment]
Yes, happy to close this off
