### ISSUE TITLE
Remove configuration signals init kwarg and attribute from StandardFlyer pending identified use case.

### ISSUE THREAD

**Issue by jwlodek** [bluesky/ophyd-async#564]
Currently in StandardDetectors we call them `config_sigs` or `_config_sigs`, and internally they are in a `list`. In the StandardFlyer, they are `configuration_signals` and are a `tuple`. We should settle on one or the other for both things.

In addition, the type hint for the flyer wants a sequence of SignalR, while for the standard detector a sequence of AsyncReadable.

Also, as mentioned in #563 , for `StandardDetector`s the signals that we typically want in `config_sigs` are instantiated with the detector, meaning they need to be set/updated after the device is initalized. Currently, you can do this with `det._config_sigs = ` or something similar, but we should probably find a way to do this without needing to access the private attribute.

**Comment by coretl** [comment]
Do we have a usecase for the ones in `StandardFlyer` yet? Otherwise I'm tempted to delete them until we have a usecase for them

**Comment by jwlodek** [comment]
I have not used them personally. I suppose all devices should be able to set their config sigs independently, so these are not really needed?
