### ISSUE TITLE
Make it easy to make a hardware backed soft signal

### ISSUE THREAD

**Issue by DominicOram** [bluesky/ophyd-async#578]
Often the soft signals on a device may be derived from the value of real hardware signals. As such, when the soft signal is read it should read the real hardware and provide its value based on this. This can be done by having the device optionally provide a readback function when creating the signal.

See https://github.com/DiamondLightSource/dodal/issues/782 for more detail on the usecase and https://github.com/DiamondLightSource/dodal/pull/789 for a solution.

**Comment by Tom-Willemsen** [comment]
This sounds quite similar to https://github.com/bluesky/ophyd-async/issues/525 , maybe good to add your use-case to that issue as well?

**Comment by DominicOram** [comment]
Thanks, I agree, closing this as a duplicate.
