### ISSUE TITLE
 Ophyd async refuses to connect to bool PVs where the set and RBV PVs have different enum values

### ISSUE THREAD

**Issue by rtuck99** [bluesky/ophyd-async#631]
dodal connect <beamline> reports many devices failing to connect with messages similar to 

```
oav: NotConnected:
    coros: NotConnected:
        drv: NotConnected:
            acquire: TypeError: Differing choices: BL22I-DI-OAV-01:DET:Acquire_RBV has ('Done', 'Acquiring'), BL22I-DI-OAV-01:DET:Acquire has ('Done', 'Acquire')
        hdf: NotConnected:
            capture: TypeError: Differing choices: BL22I-DI-OAV-01:HDF5:Capture_RBV has ('Done', 'Capturing'), BL22I-DI-OAV-01:HDF5:Capture has ('Done', 'Capture')
            acquire: TypeError: Differing choices: BL22I-DI-OAV-01:HDF5:Acquire_RBV has ('Done', 'Acquiring'), BL22I-DI-OAV-01:HDF5:Acquire has ('Done', 'Acquire')
```

Most (all?) affected are devices that inherit from `NDArrayBaseIO`
```
        self.acquire = epics_signal_rw_rbv(bool, prefix + "Acquire")
```
and 
`NDFileHDFIO`
```
        self.capture = epics_signal_rw_rbv(bool, prefix + "Capture")
```

the checks are done in ophyd_async core utils `get_unique()` which is invoked at connection time

**Comment by coretl** [comment]
I've pushed #632 which adds a test and fixes this case. Please can you check it fixes your case?

Also, I'm a little confused about the presence of `coros` in that error trace, please could you point to the `oav` implementation so I can take a look?
