### ISSUE TITLE
 Allow epics_signal_rw_rbv to use an arbitrary read PV rather than just a suffix

### ISSUE THREAD

**Issue by olliesilvester** [bluesky/ophyd-async#699]
```
def epics_signal_rw_rbv(
    datatype: type[SignalDatatypeT],
    write_pv: str,
    read_suffix: str = "_RBV",
    name: str = "",
) -> SignalRW[SignalDatatypeT]:
```
This function can currently only be used if the read back PV has the same prefix as the `write_pv`, but this is not always the case, see https://github.com/DiamondLightSource/dodal/blob/e3cf7f851f0c872d50a5f8309a134523af4ac47a/src/dodal/devices/i04/transfocator.py#L26.

I'm not sure if there's a nice way to do this. My initial thought was to add a `read_pv=None` argument which is used instead of `read_suffix` if it's been set

## Acceptance Criteria
- Functionality added, or it's decided that we don't need it

**Comment by jwlodek** [comment]
Would just using `epics_signal_rw` not work for this? It allows for specifying a read and write pv explicitly

https://github.com/bluesky/ophyd-async/blob/f7126df5e55a1a1bf00b7ad91d73165c0ea90c47/src/ophyd_async/epics/core/_signal.py#L89-L94

**Comment by olliesilvester** [comment]
> Would just using `epics_signal_rw` not work for this? It allows for specifying a read and write pv explicitly
> 
> https://github.com/bluesky/ophyd-async/blob/f7126df5e55a1a1bf00b7ad91d73165c0ea90c47/src/ophyd_async/epics/core/_signal.py#L89-L94
Ah, totally forgot about that function, thanks yeah that works!
