### ISSUE TITLE
Move contents of `sim`

### ISSUE THREAD

**Issue by coretl** [bluesky/ophyd-async#706]
When writing the docs I realize that the `sim` module isn't really a reasonable simulation of anything, I don't think it should be either. It should either be used to demo (in the tutorials) or in testing (e.g. a OneOfEveryTypeDevice). I suggest we move `ophyd_async.sim.demo` -> `ophyd_async.demo` and `ophyd_async.sim.testing` -> `ophyd_async.testing`. This gives us a nice synergy with the `epics` subpackage:

| Building blocks | Devices for tutorial | For testing core |
|-----------------|----------------------|------------------|
| ophyd_async.core            | ophyd_async.demo                 | ophyd_async.testing          |
| ophyd_async.epics.core      | ophyd_async.epics.demo           | ophyd_async.epics.testing    |
| ophyd_async.tango.core      | ophyd_async.tango.demo           | ophyd_async.tango.testing    |

**Comment by coretl** [comment]
@jwlodek @genematx thoughts?

**Comment by genematx** [comment]
Sounds sensible to me; thanks for asking, @coretl. I've been always reading `sim` here as "simulated devices for demo purposes".

**Comment by coretl** [comment]
Change all the `demo` words to `sim`
