### ISSUE TITLE
Is num=0 standard for all detectors in a flyscan?

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#83]
At the moment, flyscanning assumes that setting num=0 for the detector controller will, essentially, tell the detector to take images forever. 

There are two PR's that have been merged because this assumption turned out not to be true for pilatus detectors (#59 and #67). The question is; is this true regardless of facility? Is this just because of how our EPICS IOC's are configured for those detectors? We need to ensure the pilatus logic we have in ophyd_async.core is applicable across several institutions.

**Comment by coretl** [comment]
Decided to push the value of N up to the plan, so it will be non-zero apart from the custom plan case where it will already have been tested by the detector. Covered by #93
