### ISSUE TITLE
No longer explicitly support n=0 frames to go forever. Plan should pass this to the detectors.

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#93]
Currently, the `HardwareTriggeredFlyable` has many detectors, and calls `.arm` for all of them. By default, the signature of the `DetectorControl.arm` method has a keyword argument, `num=0` which is set to 0 by default to indicate that this controller should take infinite pictures.

This should be changed, so that actually the number of images is fixed. The easiest way of doing this is,
1. Remove the default value; this has to be passed from the Flyer.
2. Make the Flyer get this value from it's constructor
3. Test it to check it still works, e.g. on p38

This can be done in isolation to the other changes to Flyers, and is a good first issue.

**Comment by rosesyrett** [comment]
Currently, the `HardwareTriggeredFlyable` has many detectors, and calls `.arm` for all of them. By default, the signature of the `DetectorControl.arm` method has a keyword argument, `num=0` which is set to 0 by default to indicate that this controller should take infinite pictures.

This should be changed, so that actually the number of images is fixed. The easiest way of doing this is,
1. Remove the default value; this has to be passed from the Flyer.
2. Make the Flyer get this value from it's constructor
3. Test it to check it still works, e.g. on p38

This can be done in isolation to the other changes to Flyers, and is a good first issue.

**Comment by DominicOram** [comment]
Just checking that this will still leave open the possibility to allow the detector to run forever? It is a requirement for MX.

**Comment by rosesyrett** [comment]
For the MX use case, do you know in advance how many triggers could be sent to the detector?

I think the reason we decided to do this, was because we found there's no universal way to do this with detectors. We initially thought `n=0` would probably mean detectors take images forever, but on a Pilatus that's not the case and you just have to set a really high number, that doesn't even necessarily correspond with the highest number EPICs says the 'num_images' PV can take (which is really rather odd in the case of the Pilatus)

However if there's a use case for this we need to reconsider, if there is really no way we could compute ahead of time the number of images you'd need to take. Personally at that stage, I'd want to speak to people maintaining/writing the epics drivers for detectors, so we can enforce n=0 means take images forever (rather than have to guess for every detector you're using..)

**Comment by dperl-dls** [comment]
> For the MX use case, do you know in advance how many triggers could be sent to the detector?

No, the use case is not knowing in advance. We need to arm the detector before having analysed the optical images to determine the grid size (i.e. number of images)

**Comment by coretl** [comment]
And does Eiger have the concept of "forever", or do you send it a (detector specific) big number?

**Comment by coretl** [comment]
Yes, I think we can raise this to the plan level to decide how many frames the detectors should arm for. Then if you pass `n=0` down to a Pilatus it would fail, but if you pass to an Eiger it would pass. It would be the plan's responsibility to select a suitable `n`.

**Comment by coretl** [comment]
The existing code assumed all detectors could arm forever, this is the part we need to change
