### ISSUE TITLE
Rename Sim -> Mock and add SoftSignalBackend

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/ophyd-async#94]
Currently, you can set up ophyd-async devices in "sim" mode, which actually just mock out the control layer underneath (i.e. EPICs) to let someone test the stuff above it, i.e. plans and filewriting, works as expected. As such, we need to rename the "sim" interface to "mock" to prevent confusion.

**Comment by dperl-dls** [comment]
We are also using this for some totally software devices which actually do stuff - notably, getting analysis results from network services. Would it be sensible for there to be a "soft" backend which is separate from these, for clarity?

**Comment by coretl** [comment]
Does the Signal itself actually do things when you `set` it, or is it a soft signal that just takes any value you give it, and the `Device` does stuff on some suitable verb?

**Comment by dperl-dls** [comment]
The latter. The signals (RO) only take values we put to the backend with `trigger`.

**Comment by coretl** [comment]
Ok, so looks like we can do the following:

- Generic SignalR, SignalRW, SignalW, SignalX with pluggable SignalBackend
- Many implementations of SignalBackend:
  - MockSignalBackend - Backed by a Mock, used only in tests to record puts and inject values, `Signal.connect(mock=True)` uses this instead of the given backend
  - SoftSignalBackend - Used to hold a soft value that can be used by the `Device` in a verb
  - CaSignalBackend - Connection to a PV over CA
  - PvaSignalBackend - Connection to a PV over PVA
  - TangoAttributeSignalBackend - Connection to a Tango Attribute
  - ...

I'm going to suggest we remove `sim` from the system completely and instead have `fake` devices, like a `FakeMotor`, where the logic is all internal to the Device, or a `FakeBeamCurrentSimBackend` when the logic is internal to the Signal. These would be used for tutorials and in higher level software tests. Mocks are more appropriate for the unit tests in ophyd-async as they are more appropriate for running on weedy CI nodes (otherwise you get a lot of `sleep(0.2)` rather than `sleep(0.1)` because the node isn't fast enough to see things change in time)

**Comment by coretl** [comment]
Thoughts?

**Comment by Tom-Willemsen** [comment]
A similar example to David's is the [OAV pin image recognition](https://github.com/DiamondLightSource/dodal/blob/main/src/dodal/devices/oav/pin_image_recognition/__init__.py) dodal device. Like David's example, it just stores some soft parameters for later use - in this case to provide a similar API to a pre-existing device - so what you're proposed above sounds like it should work for that use-case.

**Comment by rosesyrett** [comment]
This sounds good to me @coretl. I'm going to edit the name of this ticket so it's more clear that we should be renaming Sim -> Mock, and adding a new `SoftSignalBackend` as suggested. @tpoliaw Perhaps you could use the example @Tom-Willemsen gave to implement the latter and check it works against that?

**Comment by DominicOram** [comment]
I agree with everything said so far but one additional requirement a soft `SignalR` needs a way to be able to set the value on it nicely. I've been using soft `SignalR`s to show that a signal is derived and so will be modified internally by the device but it should not be set externally through a plan.

**Comment by coretl** [comment]
> I agree with everything said so far but one additional requirement a soft `SignalR` needs a way to be able to set the value on it nicely. I've been using soft `SignalR`s to show that a signal is derived and so will be modified internally by the device but it should not be set externally through a plan. This may already be covered by existing backdoor methods but wanted to explicitly raise it.

Would something like `set_soft_value(signal, value)` work? I'm loath to change the signature to `SignalR` or make the backend public, so this is probably the best compromise.

Do you ever need to be notified if something sets the soft signal value? If so then maybe we should make a custom backend instead...

**Comment by coretl** [comment]
Actually I'm starting to think that `soft_signal_r` should just return the backend as well as the signal, that way we can just call set_value on it directly...

**Comment by DominicOram** [comment]
Or the answer is don't use a `SignalR` for this? I guess my core requirement is that I would like a soft signal that is modifiable at the Device level but not (easily) at the Plan level. I'm not too fussed about how it's implemented except a desire to make the soft and PV backed signals as similar as possible.

**Comment by coretl** [comment]
yes

**Comment by coretl** [comment]
I think this needs a bit of a design discussion, then someone can start work on it.

My thoughts:
- We need to rename the existing `SimSignalBackend` into a `SoftSignalBackend`, and remove the `set_sim_value` backends
- We need to rename the `sim` argument to `Device.connect` to `mock`
- We need to design an interface for tests to:
  - Capture calls to `signal.set`
  - Have side effects to calling `signal.set`, including blocking while we check the Device goes into a reasonable state
  - Change the values that `signal.get_value`, `signal.get_reading`, `signal.set_callback` produce

How far we need to go in functionality for the mock backend depends on the sorts of tests we will be writing. Some existing examples:
- Capture calls to `signal.set`: https://github.com/bluesky/ophyd-async/blob/feaf884e82d1dccd7096031643fd8c1246e6b9c3/tests/epics/demo/test_demo.py#L124
- Make `signal.set` block: https://github.com/bluesky/ophyd-async/blob/feaf884e82d1dccd7096031643fd8c1246e6b9c3/tests/epics/motion/test_motor.py#L69 and https://github.com/bluesky/ophyd-async/blob/feaf884e82d1dccd7096031643fd8c1246e6b9c3/tests/epics/motion/test_motor.py#L75
- Change the value of `signal.get_value`: https://github.com/bluesky/ophyd-async/blob/feaf884e82d1dccd7096031643fd8c1246e6b9c3/tests/epics/motion/test_motor.py#L51

@dperl-dls was interested in defining this interface, anyone else like to be involved in the discussion?

**Comment by DominicOram** [comment]
> @dperl-dls was interested in defining this interface, anyone else like to be involved in the discussion?

I can be involved if you like but I think I agree with all your requirements listed above @coretl

**Comment by dperl-dls** [comment]
I think that those existing examples basically cover most of the important use cases. I would really like there to be a simple wrapper around `set_sim_callback` for directing the input on one signal to another signal, e.g. letting us direct input on `device.setpoint` to `device.readback` with minimal boilerplate.

**Comment by coretl** [comment]
Some things we want out of the API:
- `with something_that_causes_put_not_to_complete_until_end(signal, value): set_some_values; check some values` on enter then make sure that put doesn't complete, then we can poke the internals, then check the object does the right thing, then on exit the put completes
- `assert_put_called_with(signal, value)` and something to reset the put mock, in a type safe way, possibly with more of the `assert_*` functions that a mock provides
- `something_that_sets_one_or_more_values(signal, *values, repeat=False, require_all_consumed=False) as cm` that either gives the same value each time, or loops through the list, either repeating or erroring when the values are exhausted, advance on an explicit `cm.advance()`
- `with something_that_sets_callback_on_put(signal, callback: Callable[[T], []])` then set the callback that is run on put on enter and remove it on exit

**Comment by evalott100** [comment]
### 1

>     * `with something_that_causes_put_not_to_complete_until_end(signal, value): 

we have

``` python
@asynccontextmanager
async def block_puts_during(*signals: List[Signal]):
``` 

### 2

>     * `assert_put_called_with(signal, value)` and something to reset the put mock, in a type safe way, possibly with more of the `assert_*` functions that a mock provides

```python
def assert_mock_put_called_with(signal: Signal, value: Any, wait=ANY, timeout=ANY):
```

works like a match:

``` python
await signal.put(5, timeout=10, wait=True)`
assert_mock_put_called_with(5) # passes
assert_mock_put_called_with(5, wait=True) # passes
assert_mock_put_called_with(5, timeout=9, wait=True) # fails
```

### 3

>     * `something_that_sets_one_or_more_values(signal, *values, repeat=False, require_all_consumed=False) as cm` that either gives the same value each time, or loops through the list, either repeating or erroring when the values are exhausted, advance on an explicit `cm.advance()`

``` python
def set_mock_values(
    signal: Signal,
    *values: List[Any],
    repeat: bool = False,
    require_all_consumed: bool = False,
) -> Iterator[Any]:
```

This is an iterator, you can do
``` python

for set_value in set_mock_values(signal, 1,2,3,4):
    print("this value was just set", set_value)
```

### 4

>     * `with something_that_sets_callback_on_put(signal, callback: Callable[[T], []])` then set the callback that is run on put on enter and remove it on exit

``` python
@contextmanager
def set_callback_on_mock_put(
    signal: Signal, callback: Callable[[T], None]
) -> Generator[None, None, None]:
```

causes the callback callable to be called whenever the backend is put to, uses the backend put args on the callable

**Comment by callumforrester** [comment]
@coretl 

> set_callback_on_mock_put(signal, callback) -> mock_put_callback(signal, callback) - More confusing, preferred the old name
> block_puts_during(*signals) -> blocking_mock_put(*signals) - Neither makes sense to me, what is this function supposed to do?

Happy with the rest

**Comment by coretl** [comment]
> > set_callback_on_mock_put(signal, callback) -> mock_put_callback(signal, callback)
> 
> More confusing, preferred the old name

Bear in mind that this is called in a `with` statement, so this will be something like:

```python
with set_callback_on_mock_put(write_sig, read_sig.set_value):
    yield from bps.mv(write_sig, 20)
    assert 20 == yield from bps.rd(read_sig)
```
How about `with callback_on_mock_put(sig, cb)`?

> > block_puts_during(*signals) -> blocking_mock_put(*signals)
> 
> Neither makes sense to me, what is this function supposed to do?

This blocks `put` until the end of the context manager, so you can do things like the motor tests:

```python
with blocking_mock_put(motor.setpoint):
    status = motor.set(0.5)
    watcher = Mock()
    status.add_watcher(watcher)
    assert_mock_put_called_with(motor.setpoint, 0.5)
    assert not status.done()
    set_mock_value(motor.readback, 0.3)
    mock.assert_called_once_with(current=0.3, ...)
assert status.done()
```

Any better ideas on names now @callumforrester ?

**Comment by dperl-dls** [comment]
I also prefer the old names for both those Callum mentioned

**Comment by coretl** [comment]
That would make it:
- `set_mock_value(signal, value)` looks fine
- `set_mock_values(signal, *values)` looks fine
- `block_puts_during(*signals)` -> `mock_puts_blocked(*signals)`
- `set_mock_put_proceeds` should be deleted and `blocking_mock_puts` used instead
- `assert_mock_put_called_with(signal, value)` looks fine
- `set_callback_on_mock_put(signal, callback)` -> `callback_on_mock_put(signal, callback)`
- `set_mock_callback` should be deleted and `assert_mock_put_called_with` or `mock_put_callback` used instead

**Comment by evalott100** [comment]
I think we should keep `set_mock_callback`: 

It allows us to pair up signals in test devices which will be used across tests:
 
https://github.com/bluesky/ophyd-async/blob/f1ec4058354a188dd90e9e60f514cb4bd00deac0/tests/epics/demo/test_demo_ad_sim_detector.py#L27-L42

It would be pretty laborious to use the context in each test using `make_detector`.

**Comment by coretl** [comment]
Good point. Can we use a single function for it? 

```python
@contextmanager
def _unset_side_effect_cm(mock):
    yield
    mock.put.side_effect = None
    
def callback_on_mock_put(sig, cb):
    backend = _get_mock_signal_backend(signal)
    backend.mock.put.side_effect = callback
    return _unset_side_effect_cm(backend.mock)
```

Then you could call it either way:
```python
with callback_on_mock_put(sig, cb):
    do_stuff()
```
or
```
@pytest.fixture
def detector():
    d = Detector()
    callback_on_mock_put(d.file_path, lambda s: set_mock_value(d.full_file_path, s)))
    yield d
```
This is the same approach you take with `open(file)`, you can either use it in a `with` statement or not

**Comment by abbiemery** [comment]
Both of these issues need addressing and have test cases. 

- [ ] Initial values on soft signals not carried through to sim #266
- [ ] Writing to soft signals fails in sim #267
